# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.srcs/sources_1/new/sevenseg_freq.v}
  {C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.srcs/sources_1/new/sevenseg_dp.v}
  {C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.srcs/sources_1/new/sevenseg.v}
  {C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.srcs/sources_1/new/parser_voltage.v}
  {C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.srcs/sources_1/new/amp_calc.v}
  {C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.srcs/sources_1/new/get_count.v}
  {C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.srcs/sources_1/new/dff.v}
  {C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.srcs/sources_1/new/get_count_sin.v}
  {C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.srcs/sources_1/new/arb_gen.v}
  {C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.srcs/sources_1/new/am_gen.v}
  {C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.srcs/sources_1/new/clk_divider.v}
  {C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.srcs/sources_1/new/display_selector.v}
  {C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.srcs/sources_1/new/display_led.v}
  {C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.srcs/sources_1/new/signal_selector.v}
  {C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.srcs/sources_1/new/frequency_selector.v}
  {C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.srcs/sources_1/new/clock_divider.v}
  {C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.srcs/sources_1/new/sine_gen.v}
  {C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.srcs/sources_1/new/triangle_gen.v}
  {C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.srcs/sources_1/new/step_sel.v}
  {C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.srcs/sources_1/new/step_calc.v}
  {C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.srcs/sources_1/new/square_gen.v}
  {C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.srcs/sources_1/new/single_pulse.v}
  {C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.srcs/sources_1/new/duty_cycle_control.v}
  {C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.srcs/sources_1/new/dc_gen.v}
  {C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.srcs/sources_1/imports/sources_1/new/myDAC_TOP.v}
}
read_vhdl -library xil_defaultlib {{C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.srcs/sources_1/imports/sources_1/imports/SourceFiles/DA2RefComp.vhd}}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.srcs/constrs_1/imports/_solution_files/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Michael/OneDrive/EE2020/Lab/Proj 30 Mar/EE2020_myDAC.srcs/constrs_1/imports/_solution_files/Basys3_Master.xdc}}]


synth_design -top myDAC_TOP -part xc7a35tcpg236-1


write_checkpoint -force -noxdef myDAC_TOP.dcp

catch { report_utilization -file myDAC_TOP_utilization_synth.rpt -pb myDAC_TOP_utilization_synth.pb }
